# Generated by Django 4.1.6 on 2023-02-04 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, verbose_name='Imię')),
                ('lastname', models.CharField(max_length=40, verbose_name='Nazwisko')),
                ('age', models.PositiveIntegerField(verbose_name='Wiek')),
                ('sex', models.CharField(choices=[('M', 'Mężczyzna'), ('F', 'Kobieta')], default='M', max_length=1, verbose_name='Płeć')),
            ],
            options={
                'verbose_name_plural': '2. Pracownicy',
                'db_table': 'employees',
                'ordering': ['lastname'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(choices=[('Kadra zarządzająca', (('DP', 'Dyrektor pionu'), ('KR', 'Kierownik'), ('LZ', 'Lider zespołu'))), ('Specjaliści i pracownicy wsparcia', (('EK', 'Ekspert'), ('SS', 'Starszy specjalista'), ('MS', 'Młodszy specjalista'))), ('Pracownicy fizyczni', (('BR', 'Brygadzista'), ('OC', 'Operator CNC'), ('PC', 'Programista CNC'), ('MT', 'Monter'), ('TK', 'Tokarz'), ('SL', 'Ślusarz'), ('FR', 'Frezer'), ('SZ', 'Szlifierz'), ('SP', 'Spawacz'), ('LK', 'Lakiernik'), ('BL', 'Blacharz'), ('OW', 'Operator wózka'), ('EL', 'Elektryk'), ('ET', 'Elektryk ds. wysokich napięć')))], default=1, max_length=2, verbose_name='Stanowisko')),
            ],
            options={
                'verbose_name_plural': '1. Stanowiska',
            },
        ),
        migrations.CreateModel(
            name='ProtectiveClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa odzieży')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Zdjęcie odzieży')),
            ],
            options={
                'verbose_name_plural': '3. Odzież ochronna',
                'db_table': 'protective_clothes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProtectiveClothingSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Skrócona nazwa zestawu odzieży BHP')),
                ('position', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bhpwoo.position', verbose_name='Stanowisko pracownika')),
                ('set', models.ManyToManyField(to='bhpwoo.protectiveclothing', verbose_name='Wybrane elementy zestawu')),
            ],
            options={
                'verbose_name_plural': '4. Zestawy odzieży ochronnej',
                'db_table': 'protective_clothes_sets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProtectiveClothingRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bhpwoo.employee', verbose_name='Pracownik otrzymujący odzież BHP')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhpwoo.protectiveclothingset', verbose_name='Wydawany zestaw')),
            ],
            options={
                'verbose_name_plural': '5. Wydanie zestawów odzieży ochronnej',
                'db_table': 'protective_clothes_release',
                'ordering': ['when'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bhpwoo.position', verbose_name='Stanowisko pracownika'),
        ),
    ]
